export const DELETE_TODO='delete_todo'
export const ADD_TODO='add_todo'
export const DELETE_COMPLETED_TODO='delete_completed_todo'
export const SELECT_ALL_TODO='select_all_todo'
export const RECEIVE_TODOS='receive_todos'